=== longdt/prism/conf/entityconf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="entityConf">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entityFields">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="rssSite" type="rssSite"
								minOccurs="0" maxOccurs="1">
							</xs:element>
							<xs:element name="listSite" type="listSite"
								minOccurs="0" maxOccurs="1">
							</xs:element>
							<xs:element name="detailSite"
								type="detailSite">
							</xs:element>
							<xs:element name="subEntity"
								type="subEntity" minOccurs="0" maxOccurs="1">
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="categories" type="categories">
				</xs:element>
			</xs:sequence>
			<xs:attribute name="backend" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="filter">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="scriptone"></xs:enumeration>
							<xs:enumeration value="scriptall"></xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="replace" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="field">
		<xs:sequence>
			<xs:element name="filter" type="filter" maxOccurs="unbounded"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="xpath" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="required" type="xs:boolean" default="true"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="mappingField">
		<xs:sequence>
			<xs:element name="filter" type="filter" maxOccurs="unbounded"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="rssField" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="entityField" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="required" type="xs:boolean" default="true"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="categories">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="category"
				type="category">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="mappingField" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="category">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute use="required" name="id" type="xs:int"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="listSite">
		<xs:sequence>
			<xs:element name="itemXpath" type="xs:string"></xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="field"
				type="field">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="detailSite">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="field"
				type="field">
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="expand"
				type="expand">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rssSite">
		<xs:sequence>
			<xs:element name="mappingField" type="mappingField"
				minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="expand">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="field"
				type="field">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="link" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="required" type="xs:boolean" default="true"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="subEntity">
		<xs:sequence>
			<xs:element name="scriptSite" type="scriptSite" minOccurs="0"
				maxOccurs="1"></xs:element>
			<xs:element name="listSite" type="listSite" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="detailSite" type="detailSite">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="link" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="scriptSite">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="xpath" type="xs:string">
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== longdt/prism/conf/sites/9film_tv/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSubEntityCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//div[@class='box_genre db']/ul[@class='genre_conter db']/li</itemXpath>
			<field xpath="span[@class='film_quality']/text()" name="filter_quality">
				<filter type="scriptone"><![CDATA[ if (!field.equals("HD")) field = null;]]></filter>
			</field>
			<field xpath="span[@class='film_note']/text()" name="tempWatch">
				<filter type="scriptone"><![CDATA[ 
					if (!field.startsWith("Tập ")) {
						field = null;
						return;
					}
					field = field.substring(4);
					var prog = field.split("/");
					if (prog.length == 2 && !prog[0].equals(prog[1])) {
						entity.setWatch(true);
					} 
				]]></filter>
			</field>
			<field xpath="div[@class='poster']/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='info-right f-right']/div[@class='poster']/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 1);
						entity.set("view", 10);
					]]>
				</filter>
			</field>
			<field xpath="//div[@class='info f-left']/h1/text()" name="title"></field>
			<field xpath="//div[@class='info f-left']/p[not(@*)]" name="description" required="false"></field>
			<field xpath="//div[@class='info-right f-right']/h3/p[strong/text() = 'Thể loại:']/a/text()" name="tags"  required="false">
				<filter type="regexall" replace=", ">\n</filter>
			</field>
		</detailSite>
		<subEntity link="//div[@class='info-right f-right']/span[@class='w-btn']/a[1]">
			<listSite>
				<itemXpath>//div[@class='server' and contains(div[@class='label'], 'Picasa')]/ul[@class='episodelist']/li/a</itemXpath>
				<field xpath="./text()" name="title">
					<filter type="scriptone">
					<![CDATA[
						entity.setSubID(field);
						if (field.length() == 1) field = "0" + field;
					]]></filter>
				</field>
				<field xpath="./@href" name="tempDetail">
					<filter type="scriptone">
						<![CDATA[
							var URL = Java.type("java.net.URL");
							var url = new URL(entity.getSourceUrl(), field);
							entity.setDetailUrl(url);
						]]>
					</filter>
				</field>
			</listSite>
			<detailSite>
				<field
				xpath="//div[@id='media']/script/text()" name="embed_web">
					<filter type="scriptone">
						<![CDATA[
							var proxyPrefix= "proxy.link\": \"";
							var index = field.indexOf(proxyPrefix);
							if (index == -1) {
								field = null;
								return;
							}
							index += proxyPrefix.length();
							var end = field.indexOf('"', index);
							field = field.substring(index, end);
							java.lang.System.out.println(field);
							var encoder = java.util.Base64.getUrlEncoder();
							var IOUtils = Java.type("org.apache.commons.io.IOUtils");
							var URL = Java.type("java.net.URL");
							try {
								var state = IOUtils.toString(new URL("http://phimdb.net/get_picasa/0/" + encoder.encodeToString(field.getBytes()).replace('_', '/')));
								if (state.length() < 10) {
									field = null;
								}
							} catch (e) {
								field = null;
							}
						]]>
					</filter>
				</field>
			</detailSite>
		</subEntity>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://9film.net/danh-sach/phim-bo/1
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/haiivl/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//*[@id='list-view-2']/div[@id='haivl-list-content']/article</itemXpath>
			<field xpath="header/div[@class='detail-info']/h2/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
						
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_id", "95");
						entity.set("type", 0);
						var ThreadLocalRandom = Java.type("java.util.concurrent.ThreadLocalRandom");
						entity.set("view", ThreadLocalRandom.current().nextInt(300, 400));
						entity.set("like_count", 0);
					]]>
				</filter>
			</field>
			<field xpath="header/div[@class='detail-info']/h2/a/text()" name="title">
				<filter type="scriptone">
					<![CDATA[ field = field.trim();
							field = field.replace("haiivl", "khuckhich");
					 ]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='content-detail']/a/img/@src" name="content">
				<filter type="scriptone">
					<![CDATA[
						field = field.trim();
						if (field.startsWith("//")) {
							field = "http:" + field;
						}
					]]>
				</filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://haivn.com/
		</category>
	</categories>
</entityConf>
