=== longdt/prism/conf/entityconf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="entityConf">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entityFields">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="rssSite" type="rssSite"
								minOccurs="0" maxOccurs="1">
							</xs:element>
							<xs:element name="listSite" type="listSite"
								minOccurs="0" maxOccurs="1">
							</xs:element>
							<xs:element name="detailSite"
								type="detailSite">
							</xs:element>
							<xs:element name="subEntity"
								type="subEntity" minOccurs="0" maxOccurs="1">
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="categories" type="categories">
				</xs:element>
			</xs:sequence>
			<xs:attribute name="backend" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="filter">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="scriptone"></xs:enumeration>
							<xs:enumeration value="scriptall"></xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="replace" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="field">
		<xs:sequence>
			<xs:element name="filter" type="filter" maxOccurs="unbounded"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="xpath" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="required" type="xs:boolean" default="true"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="mappingField">
		<xs:sequence>
			<xs:element name="filter" type="filter" maxOccurs="unbounded"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="rssField" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="entityField" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="required" type="xs:boolean" default="true"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="categories">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="category"
				type="category">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="mappingField" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="category">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute use="required" name="id" type="xs:int"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="listSite">
		<xs:sequence>
			<xs:element name="itemXpath" type="xs:string"></xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="field"
				type="field">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="detailSite">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="field"
				type="field">
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="expand"
				type="expand">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rssSite">
		<xs:sequence>
			<xs:element name="mappingField" type="mappingField"
				minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="expand">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="field"
				type="field">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="link" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="required" type="xs:boolean" default="true"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="subEntity">
		<xs:sequence>
			<xs:element name="scriptSite" type="scriptSite" minOccurs="0"
				maxOccurs="1"></xs:element>
			<xs:element name="listSite" type="listSite" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="detailSite" type="detailSite">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="link" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="scriptSite">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="xpath" type="xs:string">
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== longdt/prism/conf/sites/vuiphim/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../conf/entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//div[@class='list-flim']/div[@class='bg-list-flim']/ul/li</itemXpath>
			<field xpath="div[@class='flim-01 list_m']/div[@class='name-flim']/a/@href" name="tempField">
				<filter type="scriptone">
					<![CDATA[
						import com.ant.crawler.core.utils.PrismConstants;
						URL listSite = new URL(conf.get(PrismConstants.PLUGIN_HOME_SITE));
						URL url = new URL(listSite, field);
						field= url.toString();
						entity.setSourceUrl(url); 
						entity.set("source", url.getHost());
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", 10);
					]]>
				</filter>
			</field>
			<field xpath="div[@class='flim-01 list_m']/div[@class='name-flim']/a/text()" name="title"></field>
			<field xpath="div[@class='flim-01 list_m']/div[@class='img-flim']/h3/a/img/@src" name="thumbnail"></field>
		</listSite>
		<detailSite>
			
			<field xpath="//div[@class='move_info_type']/ul/li[contains(., 'Thể loại')]/a/text()" name="tags"  required="false">
				<filter type="scriptone"><![CDATA[
					if (field.equals("Khoa Học Viễn Tưởng")) {
						field = "Viễn Tưởng";
					}
					field = field + ",";
				]]></filter>
				<filter type="scriptall"><![CDATA[
					if (field.length() > 1) {
						field = field.substring(0, field.length() - 1);
						field = field.replace(",\n", ", ");
					}
				]]></filter>
			</field>
			<field
				xpath="//div[@class='info_detail']/*" name="description" required="false"></field>
				
			<field
				xpath="//div[@class='fiml-img']/a[@class='btn-trailer']/@href" name="embed_web">
				<filter type="scriptone"><![CDATA[
					import com.ant.crawler.core.download.Downloader;
					import org.apache.commons.io.IOUtils;
					import org.apache.commons.io.FileUtils;
					import com.solt.vttconverter.VTTConverter;
					
					String pageContent = IOUtils.toString(new URL(field));
					String moviePrefix = "<a _episode=\"1\" _link=\"";
					int movieIdx = pageContent.indexOf(moviePrefix);
					if (movieIdx == -1) {
						field = null;
						return;
					}
					movieIdx += moviePrefix.length();
					int movieEnd = pageContent.indexOf("\"", movieIdx);
					field = pageContent.substring(movieIdx, movieEnd).replace("_FREE", "");
					if (!Downloader.isGreaterLength(new URL(field), 52428800)) {
						field = null;
					} else {
						field = "direct*" + field;
					}
					
					//subtitle
					String subPrefix = "_sub=\"";
					int subIdx = pageContent.indexOf(subPrefix, movieIdx);
					if (subIdx == -1) {
						return;
					}
					subIdx += subPrefix.length();
					int subEnd = pageContent.indexOf("\"", subIdx);
					URL subURL = new URL(pageContent.substring(subIdx, subEnd));
					String subFile = "/media/thienlong/data/workspace/jee/movie/upload/subtitles/" + Downloader.getRemoteFilename(subURL) + ".vtt";
					String vtt = VTTConverter.tryConvert( new InputStreamReader(subURL.openStream()), false,false);
					FileUtils.writeStringToFile(new File(subFile), vtt);
					entity.set("sub_viet_path", subFile);
				]]></filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://vuiphim.tv/movie/movies.html
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/mphim/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//ul[@class='list_m']/li</itemXpath>
			<field xpath="a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="a[span[@class='trailer'] or span[@class='cam']]" name="filterQuality" required="false">
				<filter type="scriptone">
					<![CDATA[
						entity.setDetailUrl(null);
					]]>
				</filter>
			</field>
			<field xpath="a/span[@class='title']/text()" name="title"></field>
			<field xpath="a/span[@class='poster']/img/@data-original" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", java.util.concurrent.ThreadLocalRandom.current().nextInt(20, 50));
					]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='dt']/p[contains(., 'Thể loại: ')]/span/a/text()" name="tags"  required="false">
				<filter type="regexone" replace=", "> - </filter>
				<filter type="regexall" replace=", ">\n</filter>
			</field>

<!-- 			<field xpath="//div[@class='movie-info']/div[@class='breadcrumbs fjx-top']/style" name="btnWatch">
				<filter type="scriptone">
					<![CDATA[
						var xemphim = "http://xemphimso.com/xem-phim/online";
						var index = field.indexOf(xemphim);
						if (index == -1) {
							field = null;
							return;
						}
						var end = field.indexOf("\"", index);
						field = field.substring(index, end);
						
						var anchor = node.getHtmlPageOrNull().getFirstByXPath("//div[@class='movie-info']/div[@class='breadcrumbs fjx-top']/div[@class='item']/a");
						anchor.setAttribute("href", field);
					]]>
				</filter>
			</field> -->
			<expand link="//div[@class='dt']/p[last()]/span/a[1]">
				<field xpath="//div[@id='area_t']/script[@type='text/javascript' and not(@src)][1]/text()" name="embed_web">
					<filter type="scriptone">
						<![CDATA[
							try {
								var prefix = "{file: \"";
								var index = 0; 
								var setup = field;
								field = null;
								while ((index = setup.indexOf(prefix, index)) >= 0) {
									index += prefix.length();
									var end = setup.indexOf("\"", index);
									if (end == -1) {
										return;
									}
									var movie = setup.substring(index, end);
									java.lang.System.out.println(movie);
									if (movie.endsWith("=m22")) {
										field = "direct*" + movie;
									}
								}
							} catch (e) {
								//e.printStackTrace();
								field = null;
							}
						]]>
					</filter>
				</field>
			</expand>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://mphim.net/phim-le.html
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/phimhd3s/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//ul[@class='clearfix listmovie']/li</itemXpath>
			<field xpath="a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="a/div/p/text()" name="title"></field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='box-info']/div[@class='publish']/a[@class='hd']" name="filterQuality"></field>
			<field xpath="//div[@class='noi-dung-phim']/h1[2]/*" name="description" required="false"></field>
			<field xpath="//div[@class='box-info']/div[@class='publish']/a[position() > 1]/text()" name="tags"  required="false">
				<filter type="regexone" replace="">Phim </filter>
				<filter type="regexall" replace=", ">\n</filter>
			</field>
			<field xpath="//div[@class='fiml-img']/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", java.util.concurrent.ThreadLocalRandom.current().nextInt(40, 60));
					]]>
				</filter>
			</field>
			<field xpath="//object[@id='flashplayer']/embed/@flashvars" name="embed_web">
				<filter type="scriptone">
					<![CDATA[
					try {
						//find link
						var proxyPrefix= "proxy.link=";
						var index = field.indexOf(proxyPrefix);
						if (index == -1) {
							field = null;
							return;
						}
						index += proxyPrefix.length();
						var end = field.indexOf("&", index);
						field = field.substring(index, end);
						
						var encoder = java.util.Base64.getUrlEncoder();
						var IOUtils = Java.type("org.apache.commons.io.IOUtils");
						var URL = Java.type("java.net.URL");
						var state = IOUtils.toString(new URL("http://phimdb.net/get_picasa/0/" + encoder.encodeToString(field.getBytes()).replace('_', '/')));
						java.lang.System.out.println(state);
						if (state.length() < 10) {
							field = null;
						}
					} catch (e) {
						//e.printStackTrace();
						field = null;
					}
					]]>
				</filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://phimhd3s.net/phimle-1.html
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/sale24h/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//li[@class='threadbit hot']</itemXpath>
			<field xpath="div/div/div[@class='inner']/h3/a/text()" name="title">
				<filter type="scriptone"><![CDATA[ 
					if (field.contains("[SD]")) field = null;
					else {
						field = field.replaceAll(" \\[.*\\]", "");
					}
					]]></filter>
			</field>
			<field xpath="div/div/div[@class='inner']/h3/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var index = field.indexOf("&s=");
						if (index != -1) {
							field = field.substring(0, index);
						}
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="div/div/a/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", java.util.concurrent.ThreadLocalRandom.current().nextInt(40, 60));
					]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field
			xpath="//blockquote[@class='postcontent restore ']/font[last()]/span/a[2]/@href" name="embed_web">
				<filter type="scriptone">
					<![CDATA[
					try {
						java.lang.System.out.println(field);
						var encoder = java.util.Base64.getUrlEncoder();
						var IOUtils = Java.type("org.apache.commons.io.IOUtils");
						var URL = Java.type("java.net.URL");
						var state = IOUtils.toString(new URL("http://phimdb.net/get_picasa/0/" + encoder.encodeToString(field.getBytes()).replace('_', '/')));
						if (state.length() < 10) {
							field = null;
						}
					} catch (e) {
					}
					]]>
				</filter>
			</field>
			<field xpath="//blockquote[@class='postcontent restore ']/*" name="description" required="false"></field>
			<field xpath="//blockquote[@class='postcontent restore ']/font[1]/span/text()[1]" name="tags"  required="false">
				<filter type="regexone" replace="">Thể loại: Phim </filter>
				<filter type="regexone" replace="Hài hước">Hài</filter>
				<filter type="regexone" replace="Kinh Dị">Ma</filter>
				<filter type="regexall" replace=", ">\n</filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://sale24h.vn/raovat/forumdisplay.php?f=112
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/chatvl/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//div[@id="entries-content-ul"]/div[@class="gag-link"]</itemXpath>
			<field xpath="div[1]/div[1]/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="div[1]/div[1]/a/img[@class='thumb-img']/@src" name="thumbnail" required="false">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
					]]>
				</filter>
			</field>
			<field xpath="div[@class='post-info']/div[1]/h1/a/text()" name="title">
				<filter type="scriptone">
					<![CDATA[ field = field.trim();
						var Date = Java.type("java.util.Date");
						var today = new Date();
						entity.set("create_date", today);
						entity.set("owner_id", "1");
						entity.set("type", 2);
						var ThreadLocalRandom = Java.type("java.util.concurrent.ThreadLocalRandom");
						entity.set("view", ThreadLocalRandom.current().nextInt(300, 400));
						entity.set("like_count", 0);
					 ]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@id='video-container']/iframe/@src" name="content">
				<filter type="scriptone">
					<![CDATA[
					 var prefix = "http://chatvl.com/embed/";
					 var index = field.indexOf(prefix);
					 if (index == -1) {
					 	field = null;
					 	return;
					 }
					 
					 index += prefix.length();
					 field = field.substring(index);
					 java.lang.System.out.println(field);
					  ]]>
				</filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://chatvl.info
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/9film/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//div[@class='box_genre db']/ul[@class='genre_conter db']/li</itemXpath>
			<field xpath="span[@class='film_quality']/text()" name="filter_quality">
				<filter type="scriptone"><![CDATA[ if (!field.equals("HD")) field = null;]]></filter>
			</field>
			<field xpath="div[@class='poster']/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='info-right f-right']/div[@class='poster']/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", 10);
					]]>
				</filter>
			</field>
			<field xpath="//div[@class='info f-left']/h1/text()" name="title"></field>
			<field xpath="//div[@class='info f-left']/p[not(@*)]" name="description" required="false"></field>
			<field xpath="//div[@class='info-right f-right']/h3/p[strong/text() = 'Thể loại:']/a/text()" name="tags"  required="false">
				<filter type="regexall" replace=", ">\n</filter>
			</field>
			<expand link="//div[@class='info-right f-right']/span[@class='w-btn']/a[1]">
				<field xpath="//div[@class='server' and contains(div[@class='label'], 'Picasa')]/ul[@class='episodelist']/li/a[text() = 'Full']" name="filter_source"></field>
				<field
				xpath="//div[@id='media']/script/text()" name="embed_web">
					<filter type="scriptone">
						<![CDATA[
							var proxyPrefix= "proxy.link\": \"";
							var index = field.indexOf(proxyPrefix);
							if (index == -1) {
								field = null;
								return;
							}
							index += proxyPrefix.length();
							var end = field.indexOf('"', index);
							field = field.substring(index, end);
							java.lang.System.out.println(field);
							var encoder = java.util.Base64.getUrlEncoder();
							var IOUtils = Java.type("org.apache.commons.io.IOUtils");
							var URL = Java.type("java.net.URL");
							var state = IOUtils.toString(new URL("http://phimdb.net/get_picasa/0/" + encoder.encodeToString(field.getBytes()).replace('_', '/')));
							if (state.length() < 10) {
								field = null;
							}
						]]>
					</filter>
				</field>
			</expand>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://9film.net/danh-sach/phim-le/1
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/xemphimso/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//ul[@class='cfv']/li</itemXpath>
			<field xpath="a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="div/p/span[@class='process']/span/text()" name="filterQuality">
				<filter type="scriptone">
					<![CDATA[
						if (!field.contains("HD")) {
							field = null;
						}
					]]>
				</filter>
			</field>
			<field xpath="div/p[@class='title']/a[@title]/text()" name="title"></field>
			<field xpath="a/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", java.util.concurrent.ThreadLocalRandom.current().nextInt(20, 50));
					]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
<!-- 			<field xpath="//div[@class='movie-info']/div[@class='name-info']/h1/text() | //div[@class='movie-info']/div[@class='name-info']/h2/span/text()" name="title">
				<filter type="regexall" replace=""> \n</filter>
			</field> 
			<field xpath="//div[@id='movie_description']/*" name="description" required="false"></field>
			<field xpath="//p[@class='info_stt']/span[@class='status']/a/text()" name="tags"  required="false">
				<filter type="regexone" replace="Chiếu Rạp">Xem Phim Chiếu Rạp</filter>
				<filter type="regexone" replace="">Phim </filter>
				<filter type="regexall" replace=", ">\n</filter>
			</field>
-->
			<field xpath="//div[@class='movie-info']/div[@class='breadcrumbs fjx-top']/style" name="btnWatch">
				<filter type="scriptone">
					<![CDATA[
						var xemphim = "http://xemphimso.com/xem-phim/online";
						var index = field.indexOf(xemphim);
						if (index == -1) {
							field = null;
							return;
						}
						var end = field.indexOf("\"", index);
						field = field.substring(index, end);
						
						var anchor = node.getHtmlPageOrNull().getFirstByXPath("//div[@class='movie-info']/div[@class='breadcrumbs fjx-top']/div[@class='item']/a");
						anchor.setAttribute("href", field);
					]]>
				</filter>
			</field>
			<expand link="//div[@class='movie-info']/div[@class='breadcrumbs fjx-top']/div[@class='item']/a">
				<field xpath="//tr[td/div[@class='listserver']/span/text() = 'Server Khác :']/td[@class='listep']/a/@href" name="embed_web">
					<filter type="scriptone">
						<![CDATA[
						try {
							var IOUtils = Java.type("org.apache.commons.io.IOUtils");
							var URL = Java.type("java.net.URL");
							var pageContent = IOUtils.toString(new URL(field), "UTF-8");
							//find proxy link
							var proxyPrefix= "http://xemphimso.com/grab/vplugin2/stream2.php?file=";
							var index = pageContent.indexOf(proxyPrefix);
							if (index == -1) {
								field = null;
								return;
							}
							var end = pageContent.indexOf("&", index);
							field = pageContent.substring(index, end);
							java.lang.System.out.println("proxy link: " + field);
							
							//get google drive link
							pageContent = IOUtils.toString(new URL(field), "UTF-8");
							var prefixLink = "https://drive.google.com/file/d";
							index = pageContent.indexOf(prefixLink);
							if (index == -1) {
								field = null;
								return;
							}
							end = pageContent.indexOf("\"", index);
							field = pageContent.substring(index, end);
							var encoder = java.util.Base64.getUrlEncoder();

							var state = IOUtils.toString(new URL("http://phimdb.net/get_picasa/0/" + encoder.encodeToString(field.getBytes()).replace('_', '/')));
							java.lang.System.out.println(state);
							if (state.length() < 10) {
								field = null;
							}
							field = "<iframe src='" + field + "' width='868' height='480' frameborder='0' allowfullscreen></iframe>";
						} catch (e) {
							//e.printStackTrace();
							field = null;
						}
						]]>
					</filter>
				</field>
			</expand>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://xemphimso.com/danh-sach/phim-le/page-30.html
http://xemphimso.com/danh-sach/phim-le/page-29.html
http://xemphimso.com/danh-sach/phim-le/page-28.html
http://xemphimso.com/danh-sach/phim-le/page-27.html
http://xemphimso.com/danh-sach/phim-le/page-26.html
http://xemphimso.com/danh-sach/phim-le/page-25.html
http://xemphimso.com/danh-sach/phim-le/page-24.html
http://xemphimso.com/danh-sach/phim-le/page-23.html
http://xemphimso.com/danh-sach/phim-le/page-22.html
http://xemphimso.com/danh-sach/phim-le/page-21.html
http://xemphimso.com/danh-sach/phim-le/page-20.html
http://xemphimso.com/danh-sach/phim-le/page-19.html
http://xemphimso.com/danh-sach/phim-le/page-18.html
http://xemphimso.com/danh-sach/phim-le/page-17.html
http://xemphimso.com/danh-sach/phim-le/page-16.html
http://xemphimso.com/danh-sach/phim-le/page-15.html
http://xemphimso.com/danh-sach/phim-le/page-14.html
http://xemphimso.com/danh-sach/phim-le/page-13.html
http://xemphimso.com/danh-sach/phim-le/page-12.html
http://xemphimso.com/danh-sach/phim-le/page-11.html
http://xemphimso.com/danh-sach/phim-le/page-10.html
http://xemphimso.com/danh-sach/phim-le/page-9.html
http://xemphimso.com/danh-sach/phim-le/page-8.html
http://xemphimso.com/danh-sach/phim-le/page-7.html
http://xemphimso.com/danh-sach/phim-le/page-6.html
http://xemphimso.com/danh-sach/phim-le/page-5.html
http://xemphimso.com/danh-sach/phim-le/page-4.html
http://xemphimso.com/danh-sach/phim-le/page-3.html
http://xemphimso.com/danh-sach/phim-le/page-2.html
http://xemphimso.com/danh-sach/phim-le/page-1.html
		</category>
	</categories>
</entityConf>
