=== longdt/prism/conf/entityconf.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="entityConf">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entityFields">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="rssSite" type="rssSite"
								minOccurs="0" maxOccurs="1">
							</xs:element>
							<xs:element name="listSite" type="listSite"
								minOccurs="0" maxOccurs="1">
							</xs:element>
							<xs:element name="detailSite"
								type="detailSite">
							</xs:element>
							<xs:element name="subEntity"
								type="subEntity" minOccurs="0" maxOccurs="1">
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="categories" type="categories">
				</xs:element>
			</xs:sequence>
			<xs:attribute name="backend" type="xs:string"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="filter">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="type" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="scriptone"></xs:enumeration>
							<xs:enumeration value="scriptall"></xs:enumeration>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
				<xs:attribute name="replace" type="xs:string"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="field">
		<xs:sequence>
			<xs:element name="filter" type="filter" maxOccurs="unbounded"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="xpath" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="required" type="xs:boolean" default="true"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="mappingField">
		<xs:sequence>
			<xs:element name="filter" type="filter" maxOccurs="unbounded"
				minOccurs="0">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="rssField" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="entityField" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="required" type="xs:boolean" default="true"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="categories">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="category"
				type="category">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="mappingField" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="category">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute use="required" name="id" type="xs:int"></xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="listSite">
		<xs:sequence>
			<xs:element name="itemXpath" type="xs:string"></xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="field"
				type="field">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="detailSite">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="field"
				type="field">
			</xs:element>
			<xs:element minOccurs="0" maxOccurs="unbounded" name="expand"
				type="expand">
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="rssSite">
		<xs:sequence>
			<xs:element name="mappingField" type="mappingField"
				minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="expand">
		<xs:sequence>
			<xs:element minOccurs="1" maxOccurs="unbounded" name="field"
				type="field">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="link" type="xs:string" use="required"></xs:attribute>
		<xs:attribute name="required" type="xs:boolean" default="true"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="subEntity">
		<xs:sequence>
			<xs:element name="scriptSite" type="scriptSite" minOccurs="0"
				maxOccurs="1"></xs:element>
			<xs:element name="listSite" type="listSite" minOccurs="0" maxOccurs="1"></xs:element>
			<xs:element name="detailSite" type="detailSite">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="link" type="xs:string" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="scriptSite">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="xpath" type="xs:string">
				</xs:attribute>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
</xs:schema>

=== longdt/prism/conf/sites/phim16_tv/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ScriptSubEntityCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//div[@id='content']/div[starts-with(@class, 'post')]</itemXpath>
			<field xpath="div/a/div[@class='post-info-wrap clearfix']/span[@class='mvif vid-hd']/text()" name="filter_quality">
				<filter type="scriptone"><![CDATA[ if (!field.equals("HD")) field = null;]]></filter>
			</field>
			<field xpath="div/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="div/a/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 1);
						entity.set("view", 10);
					]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='movie-info']/h1/text() | //div[@class='movie-info']/p[@class='grtx']/text()" name="title">
				<filter type="regexall" replace=" - ">\n</filter>
			</field>
			<field xpath="//div[@class='movie-content clearfix']/*" name="description" required="false"></field>
			<field xpath="//div[@class='movie-info']/p[text()='Thể loại: ']/span/a/text()" name="tags"  required="false">
				<filter type="regexone" replace="Hàn Quốc">Hàn Quốc HD</filter>
				<filter type="regexone" replace="Hài Hước">Phim Hài</filter>
				<filter type="regexone" replace="Hoạt Hình">Phim Hoạt Hình HD</filter>
				<filter type="regexall" replace=", ">\n</filter>
			</field>
		</detailSite>
		<subEntity link="//div[@class='movie-info']/div[@class='movie-button clear']/a">
			<scriptSite xpath="//div[@id='severlist']/script[@type='text/javascript']/text()">
						<![CDATA[
							var index = field.indexOf("LINK: ");
							if (index == -1) {
								field = null;
								return;
							}
							field = field.substring(index + 6, field.length() - 1);
							
							var movies = JSON.parse(field);
							var decoder = java.util.Base64.getUrlDecoder();
							var index;
							for (index = 0; index < movies.length; ++index) {
								var movie = movies[index];
								var IOUtils = Java.type("org.apache.commons.io.IOUtils");
								var URL = Java.type("java.net.URL");
								try {
									var state = IOUtils.toString(new URL("http://sharephim.vn/get_picasa/0/" + movie.link));
									if (state.length() > 10) {
										java.lang.System.out.println(state);
										field = new java.lang.String(decoder.decode(movie.link));
										var subEntity = entity.newSubEntity();
										subEntity.setSubID(movie.name);
										if (movie.name.length() == 1) {
											movie.name = "0" + movie.name;
										}
										subEntity.set("title", movie.name);
										subEntity.set("embed_web", field);
										subEntity.set("view", 0);
									}
								} catch (e) {
								}
							}
						]]>
			</scriptSite>
			<detailSite></detailSite>
		</subEntity>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/12/
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/11/
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/10/
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/9/
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/8/
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/7/
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/6/
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/5/
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/4/
		http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/3/
			http://phim16.com/xem/tag/phim-bo-hoan-thanh/page/2/
			http://phim16.com/xem/tag/phim-bo-hoan-thanh/
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/phim16/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../conf/entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//div[@id='content']/div[starts-with(@class, 'post')]</itemXpath>
			<field xpath="div/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="div/a/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", 10);
					]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='movie-info']/h1/text()" name="title"></field>
			<field xpath="//div[@class='movie-content clearfix']/*" name="description" required="false"></field>
			<field xpath="//div[@class='movie-info']/p[text()='Thể loại: ']/span/a/text()" name="tags"  required="false">
				<filter type="regexall" replace=", ">\n</filter>
			</field>
			<expand link="//div[@class='movie-info']/div[@class='movie-button clear']/a/@href">
				<field
				xpath="//div[@id='severlist']/script[@type='text/javascript']/text()" name="embed_web">
					<filter type="scriptone">
						<![CDATA[
							var index = field.indexOf("LINK: ");
							if (index == -1) {
								field = null;
								return;
							}
							field = field.substring(index + 6, field.length() - 1);
							java.lang.System.out.println(field);
							var movies = JSON.parse(field);
							var decoder = java.util.Base64.getUrlDecoder();
							var movie = movies[movies.length - 1];
							if (movie.name == "Xem Full" || movies.length == 1) {
								field = new java.lang.String(decoder.decode(movie.link));
							} else {
								field = null;
							}
						]]>
					</filter>
				</field>
			</expand>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://phim16.com/phim/phim-hanh-dong-moi/
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/phimclub/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../conf/entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//div[@class='film']</itemXpath>
			<field xpath="h3/a/@href" name="tempField">
				<filter type="scriptone">
					<![CDATA[
						import com.ant.crawler.core.utils.PrismConstants;
						URL listSite = new URL(conf.get(PrismConstants.PLUGIN_HOME_SITE));
						URL url = new URL(listSite, field);
						field= url.toString();
						entity.setSourceUrl(url); 
						entity.set("source", url.getHost());
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", 10);
					]]>
				</filter>
			</field>
			<field xpath="h3/a/text()" name="title"></field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='move_info_type']/ul/li[contains(., 'Năm sản xuất')]/a/text()" name="tempField" required="false">
				<filter type="scriptone">
					<![CDATA[
						entity.set("title", entity.get("title") + " (" + field + ")");
					]]>
				</filter>
			</field>
			<field xpath="//img[@class='desc-left']/@src" name="thumbnail"></field>
			<field xpath="//div[@class='move_info_type']/ul/li[contains(., 'Thể loại')]/a/text()" name="tags"  required="false">
				<filter type="scriptone"><![CDATA[
					if (field.equals("Khoa Học Viễn Tưởng")) {
						field = "Viễn Tưởng";
					}
					field = field + ",";
				]]></filter>
				<filter type="scriptall"><![CDATA[
					if (field.length() > 1) {
						field = field.substring(0, field.length() - 1);
					}
				]]></filter>
			</field>
			<field
				xpath="//div[@class='move_info_type']/*" name="description"></field>
			<field
				xpath="//video[@id='player2']/source[@type='video/mp4']/@src" name="embed_web">
				<filter type="scriptone"><![CDATA[
					import com.ant.crawler.core.download.Downloader;
					if (!Downloader.isGreaterLength(new URL(field), 52428800)) {
						field = null;
					}
					field = "direct*" + field;
				]]></filter>
			</field>
			<field xpath="//video/track/@src" name="tempField1" required="false">
				<filter type="scriptone"><![CDATA[
					import com.ant.crawler.core.download.Downloader;
					import org.apache.commons.io.FileUtils;
					import com.solt.srt2vtt.SRTConverter;
					if (field.isEmpty()) {
						return;
					}
					URL subURL = new URL(field);
					String subFile = "/media/thienlong/data/workspace/jee/movie/upload/subtitles/" + Downloader.getRemoteFilename(subURL) + ".vtt";
					SRTConverter converter = new SRTConverter( new InputStreamReader(subURL.openStream()));
					FileUtils.writeStringToFile(new File(subFile), converter.toVTT(false, false));
					entity.set("sub_viet_path", subFile);
				]]></filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://phimclub.net/category/phim-le_id93
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/phimclub/newconf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../conf/entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
			<mappingField rssField="description.value" entityField="summary">
				<filter type="regexall" replace=""><![CDATA[<.*>]]></filter>
			</mappingField>
			<mappingField rssField="title" entityField="title">
				<filter type="scriptall">
					<![CDATA[entity.set("source", entity.getSourceUrl().getHost());
					entity.set("create_date", new Date());]]>
				</filter>
			</mappingField>
		</rssSite>
		<listSite>
			<itemXpath>//*[@id='news_home']/li</itemXpath>
			<field xpath="div/div[1]/a[1]/@href" name="source_url">
				<filter type="scriptone">
					<![CDATA[
						import org.w3c.dom.Attr;
						doc = node.getOwnerDocument();
						if (node instanceof Attr) {
							doc = node.getOwnerElement().getOwnerDocument();
						}
						URL listSite = new URL("http://vnexpress.net/tin-tuc/phap-luat");
						URL url = new URL(listSite, field);
						field= url.toString();
						entity.setSourceUrl(url); 
						entity.set("source", url.getHost());
						entity.set("create_date", new Date());
					]]>
				</filter>
			</field>
			<field xpath="div/div[1]/a[1]/text()" name="title"></field>
		</listSite>
		<detailSite>
			<field
				xpath="//div[@class='fck_detail width_common']" name="content"></field>
			<field
				xpath="//div[@class='short_intro txt_666']/text()"
				name="summary">
				<filter type="regexall" replace=" "><![CDATA[>.*|/]]></filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://vnexpress.net/tin-tuc/thoi-su
		</category>
		<category id="13">
		</category>
		<category id="14">
			http://vnexpress.net/tin-tuc/phap-luat
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/onb/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//div[@class="box_film"]</itemXpath>
			<field xpath="div[1]/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="div[1]/a/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", java.util.concurrent.ThreadLocalRandom.current().nextInt(10, 30));
					]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='movie_info_right']/table/tbody/tr[contains(., 'Thể Loại')]/td[2]/h2/text()" name="filter_movie">
				<filter type="scriptone">
					<![CDATA[
						if (!field.equals("Phim Lẻ")) {
							field = null;
						}
					]]>
				</filter>
			</field>
			<field xpath="//h1[@class='tenphim']/text()" name="title">
			</field>
			<field xpath="//div[@class='movie_info_right']/table/tbody/tr[contains(., 'Năm Phát Hành')]/td[2]/text()" name="tempTitle">
				<filter type="scriptone">
					<![CDATA[
						field = field.trim();
						var title = entity.get("title");
						if (!title.contains(field)) {
							entity.set("title", title + " " + field);
						}
					]]>
				</filter>
			</field>
			<field xpath="//div[@class='movie_info_right']/table/tbody/tr[contains(., 'Nhóm Phim')]/td[2]/text()" name="tags"  required="false">
				<filter type="regexone" replace=", "> - </filter>
				<filter type="regexall" replace=", ">\n</filter>
			</field>
			
			<field xpath="//html/head/title/text()" name="embed_web">
				<filter type="scriptone">
					<![CDATA[
					try {
						field = null;
						//find id
						var url = entity.getSourceUrl().toString();
						var index = url.lastIndexOf('_');
						if (index == -1) {
							return;
						}
						var id = url.substring(index + 1, url.length() - 5);
						
						//find server id
						var IOUtils = Java.type("org.apache.commons.io.IOUtils");
						var URL = Java.type("java.net.URL");
						var server = IOUtils.toString(new URL("http://movie.onb.vn/getserver.ashx?id=" + id));
						server = server.toLowerCase();
						java.lang.System.out.println(server);
						var indexFull = server.indexOf("full");
						if (indexFull == -1) {
							return;
						}
						var serverIdStart = server.lastIndexOf("id=\"", indexFull);
						if (serverIdStart == -1) {
							return;
						}
						serverIdStart += 4;
						var serverIdEnd = server.indexOf('"', serverIdStart);
						if (serverIdEnd == -1) {
							return;
						}
						var serverId = server.substring(serverIdStart, serverIdEnd);
						field = "http://www.phimrap24h.com/getlink.ashx?id=" + serverId;
						java.lang.System.out.println(field);
					} catch (e) {
						field = null;
					}
					]]>
				</filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
		<![CDATA[
		http://www.phimrap24h.com/home/movie.aspx
			]]>
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/imdb/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../conf/entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//div[@itemtype='http://schema.org/Movie']</itemXpath>
			<field xpath="table/tbody/tr[1]/td[2]/h4/a/@href" name="tempField">
				<filter type="javaone">
					<![CDATA[
						import com.ant.crawler.core.utils.PrismConstants;
						URL listSite = new URL(conf.get(PrismConstants.PLUGIN_HOME_SITE));
						URL url = new URL(listSite, field);
						field= url.toString();
						entity.setSourceUrl(url);
						entity.set("_mt", new Date());
						if (field.startsWith("http://www.imdb.com/title/tt")) {
							int index = "http://www.imdb.com/title/tt".length();
							int end = field.indexOf('/', index);
							if (end == -1) {
								end = field.length();
							}
							int imdbCode = Integer.parseInt(field.substring(index, end));
							entity.set("imdb_code", imdbCode);
						}
					]]>
				</filter>
			</field>
			<field xpath="table/tbody/tr[1]/td[2]/h4/a/text()" name="title"></field>
			<field xpath="table/tbody/tr[1]/td[1]/div/a/div/img/@src" name="cover_image"></field>
		</listSite>
		<detailSite>
			<field
				xpath="//p[@itemprop='description'] | //div[@itemprop='description']/p" name="description" required="false"></field>
			
			<field xpath="//div[@class='infobar']/a/span/text()" name="genre"  required="false">
				<filter type="javaone"><![CDATA[
					String[] tags = field.split("-");
					if (tags.length == 0) {
						return;
					}
					field = tags[0].trim() + ",";
					for (int i = 1; i < tags.length; ++i) {
						field = field + "\n" + tags[i].trim() + ",";
					}
				]]></filter>
				<filter type="javaall"><![CDATA[
					if (field.length() > 1) {
						field = field.substring(0, field.length() - 1);
						field = field.replace(",\n", ", ");
					}
				]]></filter>
			</field>
			<field xpath="//h1[@class='header']/span[@class='nobr']/a/text()" name="published_year"></field>
			<field xpath="//div[@class='star-box giga-star']/div[@class='titlePageSprite star-box-giga-star']/text()" name="imdb_score">
				<filter type="javaall">
					<![CDATA[
					field = field.trim();
				]]>
				</filter>
			</field>
			<field xpath="//div[@class='txt-block']/span[@itemprop='contentRating']/text()" name="age_rating">				
				<filter type="javaall">
					<![CDATA[
					String prefix = "Rated ";
					if (field.startsWith(prefix)) {
						int index = prefix.length();
						int end = field.indexOf(' ', index);
						if (end == -1) {
							end = field.length();
						}
						field = field.substring(index, end);
					}
					]]>
				</filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://www.imdb.com/movies-in-theaters/?ref_=inth_inth
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/thichvl/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//ul[@id="entries-content-ul"]/li[@class="gag-link"]</itemXpath>
			<field xpath="div[1]/div[1]/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="div[1]/div[1]/a/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_id", "1");
						entity.set("type", 0);
						entity.set("view", 10);
						entity.set("like_count", 0);
					]]>
				</filter>
			</field>
			<field xpath="div[1]/div[1]/a/img/@alt" name="title">
				<filter type="scriptone">
					<![CDATA[ field = field.trim(); ]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@id='content']/div[1]/div/img/@src" name="content"></field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://thichvl.net/
		</category>
	</categories>
</entityConf>

=== longdt/prism/conf/sites/xuongphim/econf.xml
<?xml version="1.0" encoding="UTF-8"?>
<entityConf xsi:noNamespaceSchemaLocation="../../entityconf.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" backend="com.ant.crawler.core.ListSiteCrawler">

	<entityFields>
		<rssSite>
		</rssSite>
		<listSite>
			<itemXpath>//ul[@id='cat_tatca']/li</itemXpath>
			<field xpath="div/div[1]/div[1]/ul/li/span/strong/text()" name="filterQuality">
				<filter type="scriptone">
					<![CDATA[
						if (!field.equals("HD")) {
							field = null;
						}
					]]>
				</filter>
			</field>
			<field xpath="div/a/@href" name="tempSource">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						entity.setDetailUrl(url);
					]]>
				</filter>
			</field>
			<field xpath="div/div[1]/p[@class]/text()" name="title">
				<filter type="regexone" replace=" - ">\n </filter>
			</field>
			<field xpath="div/a/span[1]/img/@src" name="thumbnail">
				<filter type="scriptone">
					<![CDATA[
						var URL = Java.type("java.net.URL");
						var url = new URL(entity.getSourceUrl(), field);
						field= url.toString();
						var Date = Java.type("java.util.Date");
						entity.set("create_date", new Date());
						entity.set("owner_email", "tronglongcntt@gmail.com");
						entity.set("parrent", 0);
						entity.set("view", java.util.concurrent.ThreadLocalRandom.current().nextInt(40, 60));
					]]>
				</filter>
			</field>
		</listSite>
		<detailSite>
			<field xpath="//div[@class='media-body']/div[@class='tn-contentmt']" name="description" required="false"></field>
			<field xpath="//ul[@class='filminfo-fields']/li[contains(text(), 'Thể loại')]/a/text()" name="tags"  required="false">
				<filter type="regexone" replace="Tình Cảm">Tâm Lý Tình Cảm</filter>
				<filter type="regexall" replace=", ">\n</filter>
			</field>
			<field xpath="//iframe/@src[contains(., 'drive.google.com')]" name="embed_web">
				<filter type="scriptone">
					<![CDATA[
					try {
						var encoder = java.util.Base64.getUrlEncoder();
						var IOUtils = Java.type("org.apache.commons.io.IOUtils");
						var URL = Java.type("java.net.URL");
						var state = IOUtils.toString(new URL("http://phimdb.net/get_picasa/0/" + encoder.encodeToString(field.getBytes()).replace('_', '/')));
						java.lang.System.out.println(state);
						if (state.length() < 10) {
							field = null;
						}
						field = "<iframe src='" + field + "' width='868' height='480' frameborder='0' allowfullscreen></iframe>";
					} catch (e) {
						//e.printStackTrace();
						field = null;
					}
					]]>
				</filter>
			</field>
		</detailSite>
	</entityFields>
	<categories mappingField="category_id">
		<category id="1">
			http://xuongphim.tv/danh-sach/phim-le.html
		</category>
	</categories>
</entityConf>
